server :
  port : 80

spring :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_db?serverTimezone=UTC&characterEncoding=UTF-8

    username: root
    password: securus1234

  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

  freemarker:
    cache: false

  thymeleaf:
    cache: false

  mybatis:
    config-location: classpath:mybatis-config.xml
    configuration:
      map-underscore-to-camel-case: true

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
      #location: C:\\/resources/static/common/img/
      location: /temp/uploadPath/

  custom:
    path:
      #upload-images: C:\\Users\\PHS-SECURUS\\Desktop\\mall\\src\\main\\resources\\static\\common\\img
      upload-images: /temp/uploadPath/
